load("//tools:lisp.bzl", "lisp_test")

lisp_test(
    name = "tests",
    deps = [
        "//src/util:store",
        "//src/util:hash-lock",
        "//src/util:fiveam",
        "//quicklisp:markup",
        "//src/util:mock-recording",
        "//src/pkg:pkg",
        "//src/util:bind-form",
        "//src/util:utf-8",
        "//src/util:cdn",
        "//src/util:cookies",
        "//src/util:html2text",
        "//src/util:lists",
        "//src/util:make-instance-with-accessors",
        "//src/util:mockable",
        "//src/util:mquery",
        "//src/util:object-id",
        "//src/util:ret-let",
    ],
    srcs = glob(["test-*.lisp"]),
)
