load("//tools:lisp.bzl", "lisp_test")

lisp_test(
    name = "tests",
    deps = [
        "//src/util:store",
        "//src/util:fiveam",
        "//src/util:mock-recording",
        "//src/util:util",
        "//src/pkg:pkg",
        "//src/util:utf-8",
    ],
    srcs = glob(["test-*.lisp"]),
)
