version: "3.9"
services:
  screenshotbot:
    build:
      context: ${SB_OSS_CONTEXT-.}
      dockerfile: ${SB_OSS_DOCKERFILE-Dockerfile}
    platform: linux/amd64
    ports:
      - "4091:4091"
    volumes:
      - screenshotbot-oss:/data
      - ${SB_OSS_CONTEXT-.}:/app
      - screenshotbot-build:/app/build

volumes:
  screenshotbot-oss:
  screenshotbot-build:
# test
