;;;; Copyright 2018-Present Modern Interpreters Inc.
;;;;
;;;; This Source Code Form is subject to the terms of the Mozilla Public
;;;; License, v. 2.0. If a copy of the MPL was not distributed with this
;;;; file, You can obtain one at https://mozilla.org/MPL/2.0/.

(defpackage :util/engines
  (:use #:cl)
  (:import-from #:util/request
                #:http-request-impl))
(in-package :util/engines)

(defconstant +empty-headers+ nil)

(defclass handle-misbehaving-engine ()
  ()
  (:documentation "An engine that handles a misbehaving server, and responds with a 502
instead."))

(defmethod http-request-impl ((self handle-misbehaving-engine)
                              url &rest args)
  (flet ((respond-500 (e)
           (log:warn "Faking 500 response code for ~a because of ~a" url e)
           (return-from http-request-impl
             (values
              (flexi-streams:make-in-memory-input-stream
               (flexi-streams:string-to-octets
                "<html><body>404 Not found (generated by Screenshotbot)</body></html>"))
              500
              +empty-headers+))))
    (handler-bind ((drakma::drakma-simple-error #'respond-500)
                   (simple-error
                     (lambda (e)
                       (when (equal "maybe invalid header"
                                    (format nil "~a" e))
                         (respond-500 e)))))
      (call-next-method))))
