load("//tools:lisp.bzl", "lisp_library")

lisp_library(
    name = "jvm",
    srcs = [
        "jvm.lisp",
    ],
    deps = [
        "//quicklisp:cl-fad",
        "//src/build-utils:build-utils",
    ],
    visibility = [
        "PUBLIC",
    ],
)
