load("//tools:lisp.bzl", "lisp_library", "lisp_test")

lisp_library(
    name = "encrypt",
    deps = [
        "//quicklisp:ironclad",
    ],
    srcs= [
        "encrypt.lisp",
    ],
    visibility = [
        "PUBLIC",
    ],
)

lisp_test(
    name="tests",
    deps = [
        ":encrypt",
    ],
    srcs = [
        "test-encrypt.lisp",
    ],
)
