load("//tools:lisp.bzl", "lisp_library", "lisp_test")

lisp_library(
    name = "graphs",
    srcs = [
        "dfs.lisp",
        "all.lisp",
    ],
    deps = [
        "//quicklisp:alexandria",
    ],
    visibility = [
        "PUBLIC",
    ],
)

lisp_test(
    name = "tests",
    deps = [
        ":graphs",
        "//src/util:fiveam",
    ],
    srcs = [
        "test-dfs.lisp",
    ],
)
