load("//tools:lisp.bzl", "lisp_library")

lisp_library(
    name = "build-utils",
    deps = [
        "//quicklisp:tmpdir",
    ],
    srcs = [
        "wild-module.lisp",
        "common.lisp",
        "remote-file.lisp",
        "jar-file.lisp",
        "js-package.lisp",
        "css-package.lisp",
        "intellij-plugin.lisp",
        "all.lisp",
    ],
)
